export const meta = {
  name: 'habich-runde2-erfassung',
  description: 'Habich-Runde-2: Struktur-Kartierung, Kap.2-Konventions-Research, Code-Diff E0-E4, Alt-Gegenlese, Zeichnungs-Befund',
  phases: [
    { title: 'Erfassen', detail: '5 parallele Analysten' },
    { title: 'Synthese', detail: 'Refactor-Plan-Entwurf + Verifikation' },
  ],
}

const T = 'C:/Users/benja/OneDrive/Desktop/Diplomarbeit - Datenbanken/thesis/diplomarbeit'
const CE = 'C:/Users/benja/OneDrive/Desktop/Diplomarbeit - Datenbanken/Code/external/comdare-cache-engine'
const DOCS = 'C:/Users/benja/OneDrive/Desktop/Diplomarbeit - Datenbanken/docs'

phase('Erfassen')
const A = [
  { key: 'struktur', prompt: `READ-ONLY. Kartiere den Habich-Restruktur-Zustand der Diplomarbeit in ${T}.
Der Master diplomarbeit.tex included den NEUEN 6er-Satz kapitel/de/{01_einleitung,02_suchbaeume_grundlagen,03_messsystem_prtart,04_implementierung,05_evaluation,06_fazit}.tex; die ALTEN 8 Dateien ({01_introduction,02_fundamentals,03_state_of_the_art,04_concept_architecture,05_implementation,06_evaluation_methodology,07_results_evaluation,08_conclusion}.tex) sind un-included Inhalts-Quelle ("Stufe 3 abschnittsweise umgezogen").
Aufgaben: (1) Lies alle 6 NEUEN DE-Kapitel VOLLSTAENDIG: je Kapitel Section-Gliederung + Fuellstand (SKELETT vs. ausformuliert) + [SKELETT]/TODO-Kommentare. (2) Suche in ${T}/sessions/ das Stufen-Plan-/Restruktur-Dokument (grep: Habich, Restruktur, Stufe, SKELETT, Umzug) und fasse den Plan + erledigte/offene Stufen zusammen. (3) INVENTAR fuer Habich-Kritik: Welche EIGENEN Begriffe/Konzepte/Zeichnungen (Lebewesen, Anatomie, Achsen T0-T18, Organe, Tier-Binary, Pruefling, CacheEngine, eigene tikz/verbatim-Zeichnungen) stehen im neuen Kapitel 2 (02_suchbaeume_grundlagen) und muessen nach Kap. 3? Liste mit Zeilenbereichen. (4) Wo steht die messung_driver-Zeichnung (grep in kapitel/ + anhang/ nach messung_driver/tikz/verbatim in 03_messsystem_prtart+04_implementierung) und wie sind ANDERE Zeichnungen skaliert (fontsize/scale/resizebox)? Gib Datei:Zeile.` },
  { key: 'research', prompt: `WEB-DEEP-RESEARCH (READ-ONLY lokal). Frage: Wie strukturieren vergleichbare Arbeiten (Diplom-/Masterarbeiten + Dissertationen in Datenbanken/Systems, idealerweise TU Dresden Datenbank-Gruppe Lehner/Habich, sonst international) ihr GRUNDLAGEN-/BACKGROUND-/RELATED-WORK-Kapitel?
Recherchiere per WebSearch/WebFetch: (a) 3-5 konkrete Beispiel-Arbeiten (Systems/DB-Bereich, z.B. zu Index-Strukturen, ART, in-memory DB) und deren Kap.-2-Gliederung; (b) etablierte Konventionen: Was gehoert in Background (bekannte Konzepte, Begriffsdefinitionen, Notation) vs. Related Work (Paper-Vergleich) vs. eigenes Konzept-Kapitel; wie wird die Trennung eigene-Beitraege/bekanntes Wissen gehandhabt; (c) Themenkatalog-VORSCHLAG fuer unser Kap. 2 (Thema: cache-bewusste trie-basierte Indexstrukturen, Suchbaeume, Cache-Hierarchie, Workloads/Benchmarks, wissenschaftliches Messen, C++-Metaprogrammierung/Design-Pattern als BEKANNTE Konzepte, SOTA-Paper-Korpus P01-P33) — strikt NUR Bekanntes, keine eigene Begriffswelt. Ergebnis: Gliederungs-Vorschlag Kap. 2 mit Begruendung + Quellen-URLs.` },
  { key: 'codediff', prompt: `READ-ONLY. Konsolidierungs-Diff Code->Thesis. Quellen: ${DOCS}/DIPLOMARBEIT-ZIELE-OFFENE-PUNKTE-LEDGER.md (§12-Eintraege 2026-07-09/10: Schicht-Sequenz E4->E3->E2->M->E1, Contract-Tests, Limits-Entkopplung/Codegen, Parser-Konsolidierung, EXPERIMENT_MODE), ${DOCS}/architektur/19_SCHICHTEN_FERTIGSTELLUNG_E4_E1_INTERFACE_VERTRAEGE.md + 20_HEURISTIK_MESSKURVEN_TYPSYSTEM_UND_FILTERKETTE.md + 18_MESS_METHODIK_ACHSEN_OPTIMIERUNG_KONSOLIDIERT.md (falls Pfade anders: suche in ${DOCS}/architektur bzw. ${DOCS}), Code: ${CE}/include/cache_engine/measurement/system_axis.hpp + measurement_axis_registry.hpp + i_measurement_source.hpp + curve_fit.hpp (falls Pfade abweichen: find in ${CE}).
Aufgabe: Liste ALLE seit ~2026-07-08 entstandenen Konzepte/Strukturen, die die Diplomarbeit noch NICHT beschreibt, je mit (a) Name, (b) 2-3-Satz-Erklaerung fuer die Thesis, (c) Quell-Anker Datei:Zeile, (d) Ziel-Kapitel nach neuer Struktur (Kap.3=allgemeines Konzept / Kap.4=Software-Architektur-Umsetzung / Kap.5=Evaluation): E0-E4-Schichtenmodell + Matrix-Programmierweise, Pruef-Stufen/Contract-Tests je Schicht, SystemAxis-Wurzel "Blut" + MeasurementRegime + 16 Kategorien, IMeasurementSource/Registry/curve_fit honest-empty, Hybrid-Modus (4. Modus, heuristischer Gegenbeweis: Rekombination der Tier-Binaries vs. Paper-Algorithmen), Messkurven-Typsystem + Filterkette/Chain-of-Responsibility, 3-Varianten-Observer-Messfehler-Erkennung + 4. Schritt Wall-Clock-Paper-Vergleich.` },
  { key: 'altgegenlese', prompt: `READ-ONLY. Gegenlese ALTE vs. NEUE Diplomarbeit-Version in ${T} (git). Der Tag "backup-2026-06-29-pre-habich-restruktur" (pruefe: git -C "${T}" tag -l "*habich*" bzw. "*backup*") = Stand VOR der Restruktur; ausserdem existieren die alten 8 Kapitel-Dateien noch als un-included Quelle auf der Platte.
Aufgabe: Vergleiche die ALTEN 8 Kapitel (01_introduction...08_conclusion, aktueller Platten-Stand) gegen die NEUEN 6 (01_einleitung...06_fazit): Welche FAKTEN/Ausfuehrungen/Tabellen/Zeichnungen des alten Satzes fehlen im neuen Satz komplett (nicht umgezogen, nicht als Skelett-Platzhalter vermerkt)? Ich brauche eine PRIORISIERTE Verlustliste (hoch=inhaltlich einzigartig z.B. Achsen-Sezierungs-Tabelle, Workload-Kataloge, Bib-Zitate; niedrig=redundant). Beachte: der neue Satz ist teils SKELETT — unterscheide "geplant laut Kommentar" vs. "vergessen". Gib je Verlust: altes Kapitel+Zeilenbereich, Kurzbeschreibung, Empfehlung Ziel-Ort im neuen Satz. Auch: welche \\cite-Keys des alten Satzes fehlen im neuen komplett (grep-Vergleich)?` },
  { key: 'zeichnung', prompt: `READ-ONLY. In ${T}/kapitel/de/03_messsystem_prtart.tex + 04_implementierung.tex (und falls noetig den 6 neuen Kapiteln + anhang/): Finde die messung_driver-Zeichnung (Pipeline-Zeichnung sample_data_generator -> messung_driver -> binary_to_csv -> csv_to_latex -> diagram_generator, vermutlich tikz oder verbatim/ASCII) und ALLE anderen Zeichnungen/Diagramme im neuen Kapitelsatz. Je Zeichnung: Datei:Zeile, Typ (tikz/verbatim/figure), Groessen-/Font-Steuerung (\\footnotesize/\\scriptsize/scale=/resizebox), geschaetzte Breite (laengste Zeile bei verbatim). Diagnose: Warum ist die messung_driver-Zeichnung groesser/andere Schrift-Endgroesse als die anderen? Konkreter Fix-Vorschlag (einheitliche Groessensteuerung).` },
]

const results = await parallel(A.map(a => () =>
  agent(a.prompt + '\n\nLiefere ein KOMPAKTES, strukturiertes Markdown-Ergebnis (max ~120 Zeilen), alles mit Datei:Zeile-Belegen. Erfinde nichts; Fehlendes als "nicht gefunden" markieren.', { label: 'erfasse:' + a.key, phase: 'Erfassen' })
))

phase('Synthese')
const ok = results.filter(Boolean)
const digest = ok.map((r, i) => `## ANALYST ${i}\n${String(r).slice(0, 9000)}`).join('\n\n')
const plan = await agent(`Du bist Software-/Thesis-Architekt. Aus diesen 5 Analysen einen konkreten REFACTOR-PLAN (Habich-Runde 2) entwerfen:\n${digest}\n\nVorgaben von Prof. Habich + Autor: Kap.2 STRIKT nur bekannte Konzepte/Begriffsdefinitionen/existierende Paper (KEIN eigenes Vokabular; eigene Inhalte+Zeichnungen nach Kap.3); Kap.3 = allgemeines Konzept + Begriffs-Neuschoepfung (Pruefling nicht fuehrend; §3.1 "Belange der Aufgabenstellung" neu framen, Code weiterentwickelt); Kap.4 = spezielle Software-Architektur-Umsetzung (nimmt Kap.3-Architektur-Teile); Messsystem-Idee Kap.3 / Umsetzung Kap.4; E0-E4-Schichten + Pruef-Stufen + Heuristik-Gegenbeweis (Hybrid-Modus) einarbeiten; Evaluation neu dimensioniert. Plan als geordnete Schritt-Liste (je Schritt: Quelle Datei:Zeilen -> Ziel Datei/Section, Umfangsschaetzung, Risiken), maximal ~80 Zeilen, DE-lead (EN folgt).`, { label: 'synthese:refactor-plan', phase: 'Synthese' })

return { analysen: ok, refactorPlan: plan }